name: envolet_frontend
description: "Envolet - a personal finance tracker built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  fl_chart: ^0.71.0
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^11.0.0
  http: ^1.2.0
  intl: ^0.20.2
  month_picker_dialog: ^6.2.2
  provider: ^6.1.2
  quickalert: ^1.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
